### ISSUE TITLE
Question: Can I scale-out CDC-Service in kubernetes?

### ISSUE THREAD

**Issue by muradhajiyev** [eventuate-foundation/eventuate-cdc#108]
Do I achieve load balancing when I scale out CDC-service by increasing replicas in the Kubernetes?

Another question: Can I use the current release of eventuate-saga in the commercial products/production?

**Comment by cer** [comment]
> Do I achieve load balancing when I scale out CDC-service by increasing replicas in the Kubernetes?
> 

No. For a given database server, only one CDC can be active. Others are in 'standby mode'

> Another question: Can I use the current release of eventuate-saga in the commercial products/production?

Yes.
