### ISSUE TITLE
field `published` in table message don't change after publish message

### ISSUE THREAD

**Issue by rainbowechoes** [eventuate-foundation/eventuate-cdc#139]
Hi, everyone.

I use mysql binlog + kafka in cdc service to implement transactional messaging. 

But I find field `published` in table message don't change after publish message. so if I restart cdc service again, it will send before message again.

I don't find code about update `published` filed in `MySqlBinaryLogClient`.

how should I make the sended message to be  published?

**Comment by cer** [comment]
The published column is only used by PollingDao.

MySqlBinlog saves the current file/offset in a Kafka topic.
When the CDC restarts after normal shutdown it should not republish messages.

**Comment by rainbowechoes** [comment]
Thanks for your reply!

I understand it.

Another question, I set `logging.level.root=debug`, then there is some error in console. like this:

<img width="1805" alt="image" src="https://user-images.githubusercontent.com/38370475/217755700-1c7076de-122b-4dc3-b127-4b3f2385e4d1.png">

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/38370475/217755774-d6394fde-9774-4ff9-a62b-c9265497ca97.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/38370475/217755843-7176e708-ac9e-494a-a921-47d9d26239d3.png">

cdc service works fine, but are there hidden problems if these errors are not handled?
