### ISSUE TITLE
PostgresWalClient (configurable) periodic LSN flush

### ISSUE THREAD

**Issue by klausvahter** [eventuate-foundation/eventuate-cdc#147]
It seems that PostgresWalClient flushes the LSN only if new records are inserted into the configured source table ("message" table by default). This is problematic not only in production, but also in staging environments when the database is in a shared cluster with multiple unrelated databases. Since WAL in Postgres is server-wide, then the replication slot size increases indefinitely until a new message comes into the "message" table - then it's flushed finally. This makes it hard to test the CDC service when there's still no traffic coming into the application; and it can even bring down the whole cluster if not monitored correctly.

Here's a proposal (willing to provide a PR for that): add a new configuration property through which we can define the max LSN accumulated difference size in MBs - if the diff is bigger than the accumulated size, then we flush the LSN.
Maybe we can add it to PostgresWalClient's while loop:
```
if (messageBuffer == null) {
      long lsnDiffInMb = getLsnDiffInMb(stream.getLastReceiveLSN(), stream.getLastFlushedLSN());
      saveOffsetOfLastProcessedEvent();
      if (lsnDiffInMb < MAX_LSN_DIFF_IN_MB) {
            // ...
      }   
// ... 
}
```

**Comment by cer** [comment]
Resolved
