### ISSUE TITLE
Support Oracle - Extend EventuateSqlDialect

### ISSUE THREAD

**Issue by jmone15** [eventuate-foundation/eventuate-cdc#155]
Hello all,

Currently I am trying to include support for Oracle DB to the eventuate-cdc and after having a look into the code it seems that I need to:

- Extend the `EventuateSqlDialect `as stated here https://github.com/eventuate-foundation/eventuate-cdc/issues/64
- Add the appropriate JDBC driver. Ex. `com.oracle.database.jdbc:ojdbc10:19.21.0.0`
- Rebuild the project with the additions.

Currently I am unsure of where to include the new `OracleDialect` class in order to enable it. The most probable location seems to be the `eventuate-common-jdbc` project in `eventuate-common` but this will require for me to re-build the common repository also. 

Is there an alternative way to include the extension?

Kind regards

**Comment by cer** [comment]
Sorry for the delayed response. 
I think as you discovered, eventuate-common is the best place to add the EventuateSqlDialect for Oracle.
