### ISSUE TITLE
(Question) Postgresql WAL CDC not saving last read wal position (LSN)

### ISSUE THREAD

**Issue by Inferno-88** [eventuate-foundation/eventuate-cdc#42]
I am using Eventuate Local in the project and I have a CDC service with PosgresWal in a docker container (```image eventuateio/eventuate-cdc-service:0.5.0.RELEASE```). I examined the CDC source code and I have a question about WAL offsets.

Suppose that we have an Order service that receives commands and saves the events in the event store (Postgresql). CDC service sees changes in WAL and publishes events to the Kafka. 
The next time the Order service saves the events in the event store CDC service goes down before it could publish the events to the Kafka. When CDC service come back up it doesn't know where it left off before going down, so we have events in the event store that would never get published in to the Kafka.

I can see that in ```io.eventuate.local.postgres.wal.PostgresWalCdcProcessingStatusService``` class there is```endingOffsetOfLastProcessedEvent``` attribute that is not persisted anywhere, only saved in the runtime.

Am I missing something? Is it how it supposed to work and I probably should use MySQL since it stores the offset or traditional polling?

Thanks in advance :)

**Comment by dartartem** [comment]
Here processor saves offset:

https://github.com/eventuate-foundation/eventuate-cdc/blob/0.5.0.RELEASE/eventuate-local-java-cdc-connector-postgres-wal/src/main/java/io/eventuate/local/postgres/wal/PostgresWalClient.java#L208-L210

So, when cdc restarted it continues from that offset.

If it fails to publish to kafka, there is an exception:

https://github.com/eventuate-foundation/eventuate-cdc/blob/0.5.0.RELEASE/eventuate-local-java-cdc-connector-postgres-wal/src/main/java/io/eventuate/local/postgres/wal/PostgresWalClient.java#L203

Offsets are not saved, and when cdc restarted it continues from last saved offset.

However, it can publish already published events (each offset position can contain several records, and fail can be occur when some of them already published, but offset is not saved) but there is duplicate publishing detectors, so it is not critical. Messaging consumers will detect/discard duplicate message ids.

**Comment by Inferno-88** [comment]
Thank you for pointing the direction. I was looking the wrong way. Seems like my problem with it not working was somewhere else.

**Comment by dartartem** [comment]
You are welcome. Please see examples:

https://github.com/eventuate-tram/eventuate-tram-examples-customers-and-orders
https://github.com/eventuate-examples/eventuate-examples-java-customers-and-orders
